### ISSUE TITLE
API license

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#1]
The examples in this repo access the CFC API, and this API is part of the CF subscription, and further can only be used (technically) together with CF nodes.

Using the CFC API, with valid credentials from a CF subscription, but with a non-CF software is possible technically, but is NOT licensed use of the CFC API as part of the CF subscription.

In other words, we should grant a usage license for the API with the examples, or derived code, as long as the usage is as part of a valid CF subscription.

**Comment by goeddea** [comment]
Is part of the license documents.
