### ISSUE TITLE
Namespaces and Licenses page

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#18]
The idea is for [this page](https://github.com/crossbario/crossbar-fabric-public/blob/master/docs/api/Namespaces-and-Licenses.md) to have 2 things:

* namespace overview (adapated from https://github.com/crossbario/crossbario-organize/blob/master/technology/crossbar-apis.pdf)
* links to license texts

**Comment by goeddea** [comment]
Page now has content. 

License texts are contained in the general licenses, and there is a link to the directory containing the license text.
