### ISSUE TITLE
Intro page

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#19]
[This page](https://github.com/crossbario/crossbar-fabric-public/blob/master/docs/Introduction.md) in the docs should quickly introduce CF and CFC to new users. In a technical, neutral language. This is to establish context for the "getting started" then.

The other parts of the docs are expected to be visited by users that have at least read above, or which already know CF/CFC.

**Comment by goeddea** [comment]
@oberstet - Does this fit what you wanted?

**Comment by oberstet** [comment]
perfect, yes!
