### ISSUE TITLE
Doc contrib workflow

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#2]
The original idea is to have it both: easy docs editing by using the GH wiki thing, and the use of our standard Web workflow where we use markdown files as input to a static site generator.

GH allows to get at the markdown files behind the Wiki thing by cloning a special repo URL. Great.

GH also allows us to restrict direct Wiki editing to project members with push acces. This is also what we want!

Now, we would like to allow users to fork the Wiki git repo associated with the main repo, edit the Wiki as markdown files, and then do PRs against our repo (the Wiki part).

Unfortunately, it seems, this doesn't match what GH has in mind =(

https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by meejah** [comment]
What about the new-ish "edit" buttons? As I understand it, this is "just" some nice Web UI to: clone the repo; edit the markdown; make a PR to the original repo.

That is, I think if we put markdown files directly in this docs repo, we can direct people to visit the file in *our* repo at GitHub and click the "edit" button (maybe we can even directly link from the rendered page?)

(Here is a link to "edit the README.md" in this repo to see if it works for others: https://github.com/crossbario/crossbar-fabric-docs/edit/master/README.md)

**Comment by oberstet** [comment]
@meejah good idea! I've asked stefan to try the link .. for me, obviously, it opens a source editing view on the file

**Comment by oberstet** [comment]
actually, on a side note, I've added the proxy glue bits to CFC/CF, so I'll now add an usage example into this repo. The idea is to have at least 1 example, plus some docs in the Wiki here for areas of CFC/CF..

**Comment by goeddea** [comment]
Just tried this with a fresh github account:

- The edit flow as meejah describes it works for the markdown files in the repository. Here I see an edit button, and when I press this the repository is automatically forked, I get an editor, and am guided to making a pull request.
- This does not happen with the wiki. No edit button.

--> If we want pull requests, then the docs need to be in the main repo.

**Comment by oberstet** [comment]
ok, I see. so it is either Wiki or PRs - not both. bad. in that case, I'd vote for putting markdown files in main repo, so we can have PRs.

**Comment by goeddea** [comment]
+1 on markdown in the main repo. It makes little difference regarding the usability when browsing the docs on GitHub itself.

**Comment by meejah** [comment]
We could make the Flask stuff burn-in "edit" links, too (e.g. something moderately-noticeable like "See a mistake? Edit this page" or similar.

**Comment by oberstet** [comment]
Ok, I have moved the docs to the main repo. The "burn in" buttons to edit: +1

**Comment by oberstet** [comment]
I have added "edit me on GH" link generation to the markdown site generator. so we have it!
