### ISSUE TITLE
Example driver should move to cbsh

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#5]
`client.run()` could really be a library function from the `crossbarfabricshell` package (the main thing being `cbsh` of course).

The driver would then also need to be rewritten into asyncio style, since otherwise we introduce another dependency (Twisted) into above shell package.

**Comment by om26er** [comment]
Do you think this is something I could work on ? In such a case is this the [code](https://github.com/crossbario/crossbar-fabric-docs/blob/master/examples/client.py) that need to be ported to asyncio and moved to cbsh codebase ?

**Comment by oberstet** [comment]
@om26er yeah, if you want to port it etc, that would be highly welcome of course!

**Comment by oberstet** [comment]
other things that would be neat:
* try the examples here, and see if it works for you. testing, feedback, ..
* when you are ready, add an example for controlling docker via CFC/CF here;)

**Comment by oberstet** [comment]
@om26er actually, above means that the examples here need to be modified for asyncio flavor too - also sth you could take up in the course naturally ..

**Comment by om26er** [comment]
PR https://github.com/crossbario/crossbar-fabric-docs/pull/8 ports the examples and client to asyncio. The client.py in cbsh and -docs are mostly doing similar things, I am working to consolidate the two.

**Comment by om26er** [comment]
> PR crossbario#8 ports the examples and client to asyncio. The client.py in cbsh and -docs are mostly doing similar things, I am working to consolidate the two.

Here: https://github.com/crossbario/crossbar-fabric-shell/pull/4

**Comment by oberstet** [comment]
great! I port over the examples and remove the code here ..

**Comment by oberstet** [comment]
this is done
