### ISSUE TITLE
Port examples

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-fabric-public#7]
Port over the examples from https://github.com/crossbario/crossbar-examples/tree/master/fabric/api

**Comment by om26er** [comment]
@oberstet should they just be ported to asyncio and copied under this project ?

**Comment by oberstet** [comment]
actually, the fabric examples from the "crossbar-examples" repo should be ported and _moved_ here (disappear in the former repo).

**Comment by oberstet** [comment]
there wasn't a lot, but it's ported now (and removed from the CB examples repo)
